[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites_program = "7ghGdpBu5LJP8V6HpddAjtjue8SEa9qG6T7BqaHjKxeY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../main-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
